// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/yulefox/lamp/kits/something (interfaces: MyInterface)

package mock_something

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of MyInterface interface
type MockMyInterface struct {
	ctrl     *gomock.Controller
	recorder *_MockMyInterfaceRecorder
}

// Recorder for MockMyInterface (not exported)
type _MockMyInterfaceRecorder struct {
	mock *MockMyInterface
}

func NewMockMyInterface(ctrl *gomock.Controller) *MockMyInterface {
	mock := &MockMyInterface{ctrl: ctrl}
	mock.recorder = &_MockMyInterfaceRecorder{mock}
	return mock
}

func (_m *MockMyInterface) EXPECT() *_MockMyInterfaceRecorder {
	return _m.recorder
}

func (_m *MockMyInterface) AnotherMethod(_param0 int64, _param1 string, _param2 bool) {
	_m.ctrl.Call(_m, "AnotherMethod", _param0, _param1, _param2)
}

func (_mr *_MockMyInterfaceRecorder) AnotherMethod(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AnotherMethod", arg0, arg1, arg2)
}

func (_m *MockMyInterface) SomeMethod(_param0 int64, _param1 string) {
	_m.ctrl.Call(_m, "SomeMethod", _param0, _param1)
}

func (_mr *_MockMyInterfaceRecorder) SomeMethod(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SomeMethod", arg0, arg1)
}
